import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import buttons from "../data/buttons.json";
import Button from "./Button";

const Home = () => {
  const [display, setDisplay] = useState("0");

  const operators = ["+", "-", "*", "/"];

  const buttonClick = (val: string) => {
    const lastCharOfDisplay = display[display.length - 1];
    if (operators.includes(lastCharOfDisplay) && operators.includes(val))
      setDisplay((prev) => prev.slice(0, -1) + val);
    else setDisplay((prev) => (prev !== "0" ? prev + val : val));
  };

  const clearDisplay = () => setDisplay("0");

  const calculate = () => {
    if (!operators.includes(display[display.length - 1]))
      setDisplay(eval(display));
  };

  return (
    <>
      <Head>
        <title>JavaScript Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/calculator.ico" />
      </Head>
      <main className={styles.main}>
        <div id="display">{display}</div>
        {buttons.map((el) => {
          return (
            <Button
              key={el.id}
              id={el.id}
              val={el.val}
              handleButton={buttonClick}
            />
          );
        })}
        <Button id="clear" val="C" handleButton={clearDisplay} />
        <Button id="equals" val="=" handleButton={calculate} />
      </main>
    </>
  );
};

export default Home;
