import Head from "next/head";
import styles from "@/styles/Home.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>JavaScript Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/calculator.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
};

export default Home;
